export const data = {
    "result":{
        "codeEnum":"Success",
        "statusCode":200,
        "msg":"请求(或处理)成功",
        "data":[
            {
                "costCenterId":1,
                "costCenterCode":"NWSC.LNXM.LN3.CC01.CC01",
                "costCenterName":"成本中心1",
                "elementBudgetItemTree":{
                    "elementInfoId":0,
                    "elementInfoCode":"NWCL",
                    "elementInfoNameCN":"预算科目",
                    "parentID":-1,
                    "orderSeq":1,
                    "amount":0,
                    "percentage":0,
                    "planDetailId":0,
                    "childs":[
                        {
                            "elementInfoId":36,
                            "elementInfoCode":"C",
                            "elementInfoNameCN":"建安费",
                            "parentID":0,
                            "orderSeq":35,
                            "amount":0,
                            "percentage":0,
                            "planDetailId":0,
                            "childs":[
                                {
                                    "elementInfoId":38,
                                    "elementInfoCode":"TempBACKUP_C-1-1",
                                    "elementInfoNameCN":"開辦費",
                                    "parentID":36,
                                    "orderSeq":37,
                                    "amount":0,
                                    "percentage":0,
                                    "planDetailId":0,
                                    "childs":[

                                    ],
                                    "tradeBudgetItems":[
										
                                        {
                                            "budgetValue":1,
                                            "id":1
                                        },
                                        {
                                            "budgetValue":2,
                                            "id":2
                                        },
                                        {
                                            "budgetValue":3,
                                            "id":3
                                        },
                                        {
                                            "budgetValue":4,
                                            "id":4
                                        },
                                        {
                                            "budgetValue":5,
                                            "id":5
                                        },
                                        {
                                            "budgetValue":6,
                                            "id":6
                                        },
                                        {
                                            "budgetValue":7,
                                            "id":7
                                        },
                                        {
                                            "budgetValue":8,
                                            "id":8
                                        },
                                        {
                                            "budgetValue":9,
                                            "id":9
                                        },
                                        {
                                            "budgetValue":10,
                                            "id":10
                                        }
										
                                    ],
                                    "creatorUser":null,
                                    "creationTime":"0001-01-01T00:00:00",
                                    "lastModifierUser":null,
                                    "lastModificationTime":null,
                                    "isAudit":false,
                                    "auditStatus":null,
                                    "auditTime":null,
                                    "id":0
                                },
                                {
                                    "elementInfoId":40,
                                    "elementInfoCode":"TempBACKUP_C-1-2",
                                    "elementInfoNameCN":"结构及土建工程",
                                    "parentID":36,
                                    "orderSeq":39,
                                    "amount":0,
                                    "percentage":0,
                                    "planDetailId":0,
                                    "childs":[

                                    ],
                                    "tradeBudgetItems":[

                                    ],
                                    "creatorUser":null,
                                    "creationTime":"0001-01-01T00:00:00",
                                    "lastModifierUser":null,
                                    "lastModificationTime":null,
                                    "isAudit":false,
                                    "auditStatus":null,
                                    "auditTime":null,
                                    "id":0
                                },
                                {
                                    "elementInfoId":46,
                                    "elementInfoCode":"TempBACKUP_C-1-3",
                                    "elementInfoNameCN":"外立饰面工程",
                                    "parentID":36,
                                    "orderSeq":45,
                                    "amount":0,
                                    "percentage":0,
                                    "planDetailId":0,
                                    "childs":[

                                    ],
                                    "tradeBudgetItems":[

                                    ],
                                    "creatorUser":null,
                                    "creationTime":"0001-01-01T00:00:00",
                                    "lastModifierUser":null,
                                    "lastModificationTime":null,
                                    "isAudit":false,
                                    "auditStatus":null,
                                    "auditTime":null,
                                    "id":0
                                },
                                {
                                    "elementInfoId":61,
                                    "elementInfoCode":"TempBACKUP_C-1-4",
                                    "elementInfoNameCN":"室内装饰及精裝修工程(包括精裝及粗装修)#",
                                    "parentID":36,
                                    "orderSeq":60,
                                    "amount":0,
                                    "percentage":0,
                                    "planDetailId":0,
                                    "childs":[

                                    ],
                                    "tradeBudgetItems":[

                                    ],
                                    "creatorUser":null,
                                    "creationTime":"0001-01-01T00:00:00",
                                    "lastModifierUser":null,
                                    "lastModificationTime":null,
                                    "isAudit":false,
                                    "auditStatus":null,
                                    "auditTime":null,
                                    "id":0
                                },
                                {
                                    "elementInfoId":68,
                                    "elementInfoCode":"TempBACKUP_C-1-5",
                                    "elementInfoNameCN":"机电工程",
                                    "parentID":36,
                                    "orderSeq":67,
                                    "amount":0,
                                    "percentage":0,
                                    "planDetailId":0,
                                    "childs":[

                                    ],
                                    "tradeBudgetItems":[

                                    ],
                                    "creatorUser":null,
                                    "creationTime":"0001-01-01T00:00:00",
                                    "lastModifierUser":null,
                                    "lastModificationTime":null,
                                    "isAudit":false,
                                    "auditStatus":null,
                                    "auditTime":null,
                                    "id":0
                                },
                                {
                                    "elementInfoId":88,
                                    "elementInfoCode":"TempBACKUP_C-1-6",
                                    "elementInfoNameCN":"LEED及绿色建筑所需費用",
                                    "parentID":36,
                                    "orderSeq":87,
                                    "amount":0,
                                    "percentage":0,
                                    "planDetailId":0,
                                    "childs":[

                                    ],
                                    "tradeBudgetItems":[

                                    ],
                                    "creatorUser":null,
                                    "creationTime":"0001-01-01T00:00:00",
                                    "lastModifierUser":null,
                                    "lastModificationTime":null,
                                    "isAudit":false,
                                    "auditStatus":null,
                                    "auditTime":null,
                                    "id":0
                                },
                                {
                                    "elementInfoId":90,
                                    "elementInfoCode":"TempBACKUP_C-1-7",
                                    "elementInfoNameCN":"營運單位所需預算項目(请按需要再分列细项):",
                                    "parentID":36,
                                    "orderSeq":89,
                                    "amount":0,
                                    "percentage":0,
                                    "planDetailId":0,
                                    "childs":[

                                    ],
                                    "tradeBudgetItems":[
										
										    {
										        "budgetValue":11,
										        "id":11
										    },
										    {
										        "budgetValue":12,
										        "id":12
										    },
										    {
										        "budgetValue":13,
										        "id":13
										    },
										    {
										        "budgetValue":14,
										        "id":14
										    },
										    {
										        "budgetValue":15,
										        "id":15
										    },
										    {
										        "budgetValue":16,
										        "id":16
										    },
										    {
										        "budgetValue":17,
										        "id":17
										    },
										    {
										        "budgetValue":18,
										        "id":18
										    },
										    {
										        "budgetValue":19,
										        "id":19
										    },
										    {
										        "budgetValue":20,
										        "id":20
										    }
										
                                    ],
                                    "creatorUser":null,
                                    "creationTime":"0001-01-01T00:00:00",
                                    "lastModifierUser":null,
                                    "lastModificationTime":null,
                                    "isAudit":false,
                                    "auditStatus":null,
                                    "auditTime":null,
                                    "id":0
                                }
                            ],
                            "tradeBudgetItems":[

                            ],
                            "creatorUser":null,
                            "creationTime":"0001-01-01T00:00:00",
                            "lastModifierUser":null,
                            "lastModificationTime":null,
                            "isAudit":false,
                            "auditStatus":null,
                            "auditTime":null,
                            "id":0
                        }
                    ],
                    "tradeBudgetItems":[

                    ],
                    "creatorUser":null,
                    "creationTime":"0001-01-01T00:00:00",
                    "lastModifierUser":null,
                    "lastModificationTime":null,
                    "isAudit":false,
                    "auditStatus":null,
                    "auditTime":null,
                    "id":0
                }
            }
        ]
    },
    "targetUrl":null,
    "success":true,
    "error":null,
    "unAuthorizedRequest":false,
    "__abp":true
}